### ISSUE TITLE
Add the package to Stackage

### ISSUE THREAD

**Issue by mrkkrp** [kaoskorobase/hsndfile#13]
If you don't mind, I need this stuff to be in Stackage. I can add it myself, if you're lazy ;-)

https://github.com/fpco/stackage/#get-your-package-included

**Comment by kaoskorobase** [comment]
In principle I think it's a good idea, but do you know how Stackage handles external dependencies? E.g. `hsndfile` needs `libsndfile` development packages installed.

**Comment by mrkkrp** [comment]
That's OK, I recently added my [`htaglib`](https://github.com/mrkkrp/htaglib) which depends on `libtag_c` (if memory serves me well). You just will need to know name of Ubuntu package that provides your dependency, so they can include it in their list of packages that have to be installed for testing.

**Comment by kaoskorobase** [comment]
OK, thanks, I've submitted a pull request [here](https://github.com/fpco/stackage/pull/980).

**Comment by mrkkrp** [comment]
@kaoskorobase, I see that it's merged. Thank you! Closing this.
