### ISSUE TITLE
Build failure due to c2hs error

### ISSUE THREAD

**Issue by kaoskorobase** [kaoskorobase/hsndfile#14]
[Build fails](https://travis-ci.org/kaoskorobase/hsndfile/builds/91813099) due to a `c2hs` error:

```
c2hs: Errors during expansion of binding hooks:
/usr/include/sndfile.h:337: (column 1) [ERROR]  >>> Illegal use of incomplete type!
  Expected a fully defined structure or union tag; instead found incomplete type.
/usr/include/sndfile.h:337: (column 1) [ERROR]  >>> Illegal use of incomplete type!
  Expected a fully defined structure or union tag; instead found incomplete type.
```

Probably related to [this issue](https://github.com/haskell/c2hs/issues/152).

**Comment by mrkkrp** [comment]
Is there a way I can make it work for now?

**Comment by kaoskorobase** [comment]
I've just added an upper bound of `< 0.26` to the `c2hs` build tool dependency (see https://github.com/fpco/stackage/issues/980). Could you check if that works for you? You might have to reinstall `c2hs`.

**Comment by kaoskorobase** [comment]
You probably need to install the correct version explicitly:

```
cabal install c2hs-0.25.2
```
