### ISSUE TITLE
Recommendations how to calculate peak

### ISSUE THREAD

**Issue by mrkkrp** [kaoskorobase/hsndfile#15]
I've finally installed `hsndfile`. I have no problem performing lookups of various parameters of files, but one more thing that I want to accomplish is calculation of peak sample. I've studied API, but unfortunately I cannot find instances of `Buffer` type class. How to use it?

Can you give a hint how can I approach calculation of peak sample?

**Comment by mrkkrp** [comment]
It seems like this package is not usable without another package `hsndfile-vector`. So it should be added to Stackage too (once problem with `c2hs` is solved). This is rather strange, it would be more handy to include implementation of `Buffer` instance for `Vector` in `hsndfile` package. For me it was not obvious that I need another package to actually do something, and I only recognized that after looking at `examples` directory.

You, of course, perhaps have arguments why such division into different packages is necessary…

**Comment by mrkkrp** [comment]
On the other hand that `hsndfile-vector` package is uploaded last time in 2011. Maybe it's not that necessary.

**Comment by mrkkrp** [comment]
OK, I handled this. Consider adding a comment there about other packages that are needed to actually work with `Buffer`, I find it not obvious. Closing.

**Comment by kaoskorobase** [comment]
Hi, thanks for the report, I've added two new related issues. I don't have time to work on this right now, pull requests welcome!
