### ISSUE TITLE
Write to `stdout`

### ISSUE THREAD

**Issue by soenkehahn** [kaoskorobase/hsndfile#20]
Is there an easy way to use `hsndfile` to write a sound file to `stdout` (which is of type `System.IO.Handle`)? I don't see a way to do that with the exposed API. (Except writing to a temporary file and then reading the contents back in and writing that to `stdout`.)

**Comment by kaoskorobase** [comment]
Hi Sönke! Long time no see 😀 It's currently not possible in Haskell but could be possible by wrapping libsndfile's virtual IO API: http://www.mega-nerd.com/libsndfile/api.html#open_virtual

**Comment by soenkehahn** [comment]
Hi Stefan, yeah, it's been a while. :)

I've implemented a wrapper that goes the route through a temporary file now. If that ever becomes a problem, I might come back to `sf_open_virtual`.

(Closing this to not clutter the issue tracker.)
